### ISSUE TITLE
2017-2020 DEX

### ISSUE THREAD

**Issue by graetzelena** [COVIDExposureIndices/COVIDExposureIndices#10]
I first wanted to thank everyone's work and effort on this data, and also for making it publicly available. 

We are working on a study using the DEX and comparing it to hospital trends. Similarly to seeing seasonal patterns in hospitalizations, it would add robustness to see the DEX over the years prior to COVID. 

Is anonymized, aggregated smartphone movement data provided by [PlaceIQ] available prior to 2020 and if so, is it possible to create the DEX for the previous years based on the code and work you have already done?

**Comment by jdingel** [comment]
Data prior to 2020 is not available for these purposes.
