### ISSUE TITLE
Any plans on international data?

### ISSUE THREAD

**Issue by robroc** [COVIDExposureIndices/COVIDExposureIndices#2]
Is there data for other countries? Any plans to release it, or are there other groups working on this?

**Comment by awasgreen** [comment]
We only have data for the US.

Apple released mobility data (https://www.apple.com/covid19/mobility) that includes international locations. However, it is restricted to countries and major cities. There is also mobility data from the citymapper app (https://citymapper.com/cmi) that includes cities internationally. There might be other sources of international data out there but those are two I'm aware of off the top of my head.

**Comment by jdingel** [comment]
Roberto, if you are interested in data on Canada, you might look at the TELUS Data for Good initiative: https://www.telus.com/en/about/covid-19-updates/privacy-statement
