### ISSUE TITLE
Hotspots

### ISSUE THREAD

**Issue by asolow** [COVIDExposureIndices/COVIDExposureIndices#4]
This is incredibly helpful! Would it be possible to share or publish the index at smaller geographic units? NYC neighborhood for example?
Thanks!
Anna

**Comment by jdingel** [comment]
We are not publishing these indices for geographic units smaller than counties at this time. We hope that the DEX-income, DEX-race, and DEX-education measures will allow researchers to explore how these DEX measures vary by neighborhood characteristics even without accessing neighborhood-level observations.

If there are neighborhood characteristics other than income, education, and racial/ethnic demographics that would be useful for your research application, please do let us know.
