### ISSUE TITLE
LEX denominator at state level?

### ISSUE THREAD

**Issue by chengweigogo** [COVIDExposureIndices/COVIDExposureIndices#6]
Great work! Thanks very much for sharing the data for research. I'm wondering is there a way to get the number of devices that ping in each state (the denominator for state LEX)? This data for the 2,018 counties are available, but summing up counties won't give us a state total, right? since some counties are not covered. Thanks and looking forward to your kind reply!

**Comment by c3-robertyoung** [comment]
From my understanding, summing counties also won't yield accurate state values because phones can ping in multiple counties on a single date, so they would be double-counted. Are you planning to implement a `state_devicescount.csv`?

**Comment by jdingel** [comment]
You are correct, you cannot construct state totals from county totals. We will try to get back to you on this soon. Thanks!

**Comment by jdingel** [comment]
Hi, these counts are now available in `lex_data/state_devicescount.csv`. I apologize that we were slow to address this request.

**Comment by c3-robertyoung** [comment]
Thank you! This is very helpful.

**Comment by chengweigogo** [comment]
Indeed! Thank you very much!


On 6/12/2020 23:34，Robert Young<notifications@github.com> wrote：

Thank you! This is very helpful.
